name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 关键：所有命令都在 env-calculator 目录执行
defaults:
  run:
    working-directory: env-calculator

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: env-calculator/package-lock.json

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build

      - name: Health check (local)
        run: |
          npm run dev &
          PID=$!
          sleep 8
          npm run test:storage || true
          kill $PID

